services:
  robotica_jazzy:
    image: diplomado_jazzy
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: robotica_jazzy
    gpus: all
    network_mode: host
    privileged: true
    user: "ros"
    working_dir: /home/ros/ros_ws
    tty: true
    stdin_open: true
    command: bash
    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY} # Forward X11 display
      NVIDIA_DRIVER_CAPABILITIES: all #compute,utility,graphics # Allow GPU access
      NVIDIA_VISIBLE_DEVICES: all # Expose all GPUs
      QT_X11_NO_MITSHM: 1
    devices:
      - "/dev/dri:/dev/dri" # Allow OpenGL rendering
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD:/home/ros/ros_ws
